### ISSUE TITLE
How to Push view to Hide Tabbar?

### ISSUE THREAD

**Issue by 350887156** [forXifLess/LinkNavigator#37]
How to Push view to Hide Tabbar?

**Comment by 97chos** [comment]
Hi, @350887156.
Thank you for using LinkNavigator!

Since you didn't provide the specific code or detailed requirements you want to apply, I can't offer a detailed solution, but you can declare `TabLinkNavigationView` with `isHiddenDefaultTabbar` set to `false` and customize the Tabbar in the main pages of each tab.

If you have any additional questions, please leave a comment.

Thank you.

**Comment by njraweng** [comment]
Hi @97chos,

Can we hide the tab bar when a view is pushed? I have checked TabLinkNavigationView with isHiddenDefaultTabbar set to false, but our use case requires hiding the tab bar on push. Is this achievable via LinkNavigator?

Thank you

**Comment by njraweng** [comment]
@97chos @350887156  I have raised a pull request for the feature to hide tab bar when the view is pushed Please review it and let me know if you have any feedbacks https://github.com/forXifLess/LinkNavigator/pull/39

**Comment by 97chos** [comment]
Hello, @njraweng !

Thank you for using LinkNavigator in your project.

For your use case, you can hide the DefaultTabbar and implement a CustomTabbar instead. This way, you can implement the Tabbar only on the page corresponding to Tab1 and not on any other pages.

We have also reviewed the excellent PR you submitted. It will be reviewed internally and integrated, though this may take some time due to internal processes.

In the meantime, I recommend solving the issue with the method I proposed above until the PR is integrated.

Thank you for your interest!
